ARG LAUNCHER_VERSION=latest

# +========================+
# |      BUILD  STAGE      |
# +========================+
FROM alpine:3.23.4 AS builder
WORKDIR /app

ARG MODULE_GROUP
ARG MODULE_NAME
ARG MODULE_VERSION

RUN GROUP_PATH=$(echo ${MODULE_GROUP} | tr "." "/") && \
    wget -q -O "${MODULE_GROUP}~${MODULE_NAME}~${MODULE_VERSION}-fat.jar" "https://maven.opendigitaleducation.com/repository/public/${GROUP_PATH}/${MODULE_NAME}/${MODULE_VERSION}/${MODULE_NAME}-${MODULE_VERSION}-fat.jar" && \
    mkdir -p /app/${MODULE_GROUP}~${MODULE_NAME}~${MODULE_VERSION} && \
    unzip -q "${MODULE_GROUP}~${MODULE_NAME}~${MODULE_VERSION}-fat.jar" -d /app/${MODULE_GROUP}~${MODULE_NAME}~${MODULE_VERSION} && \
    rm "${MODULE_GROUP}~${MODULE_NAME}~${MODULE_VERSION}-fat.jar"

# +========================+
# |      LAUNCH STAGE      |
# +========================+
FROM opendigitaleducation/vertx-service-launcher:${LAUNCHER_VERSION}

LABEL org.opencontainers.image.source=https://github.com/Mon-ENT/images-docker
LABEL org.opencontainers.image.licenses=GPL-3.0-or-later
LABEL maintainer="Micorksen <hello@micorksen.eu>"

ARG MODULE_GROUP
ARG MODULE_NAME
ARG MODULE_VERSION

COPY --from=builder /app/ /srv/springboard/mods
ENV ENABLED_SERVICES=${MODULE_GROUP}~${MODULE_NAME}
ENV MODE=cluster
ENV MODULE_VERSION=${MODULE_VERSION}